import React from "react";
import { useState, useEffect } from "react";
import { Loader, FormField, Card } from "../components";
import { Heading2, Section } from "lucide-react";

const RenderCards = ({ data, title }) => {
  // if length>0 return data then return a self closing component and ...post spread out the post properties
  if (data?.length > 0)
    return data.map((post) => <Card key={post.id} {...post} />);

  // else
  return (
    <h2 className="mt-5 font-bold text-[#6469ff] text-xl uppercase">{title}</h2>
  );
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState([]);
  const [searchText, setSearchText] = useState("");

  return (
    <section className="max-w-7xl mx-auto">
      <div className="text-left">
        <h1 className="font-extrabold text-[#222328] text-[32px] ">
          The Community Showcase
        </h1>
        <p className="mt-2 text-[#666e75] text-[16px] max-w-[700px]">
          Browse through a collection of visually stunning images generated by
          AI
        </p>
      </div>
      <div className="mt-16 text-left">
        <FormField />
        <div className="mt-10">
          {loading ? (
            <div className="flex justify-center items-center">
              <Loader />
            </div>
          ) : (
            <>
              {searchText && (
                <h2 className="font-medium text-[#666e75] text-xl mb-3">
                  Showing results for{" "}
                  <span className="text-[#222328]">{searchText}</span>
                </h2>
              )}
              <div className="grid ld:grid-col-4 sm:grid-col-3 xs:grid-col-2 grid-cols-1 gap-3">
                {searchText ? (
                  <RenderCards data={[]} title="No search results found" />
                ) : (
                  <RenderCards data={[]} title="No Posts found" />
                )}
              </div>
            </>
          )}
        </div>
      </div>
    </section>
  );
};

export default Home;
